### ISSUE TITLE
Put User Workspaces REST API behind AWS API Gateway

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/aws-api-gateway#2]
Endpoints from Juan:
```
POST /tokens/

GET /workspaces/
GET /workspaces/<workspace_id>
GET /workspaces/?query_params
POST /workspaces/
PUT /workspaces/<workspace_id>

GET /jobs/
GET /jobs/<job_id>
GET /jobs/?query_params
PUT /jobs/<job_id>

GET /job_types/
```

Two items need further attention:

1. I'm not sure how AWS API Gateway would handle the endpoints with query string. Things like
```
GET /jobs/
GET /jobs/?query_params
```
will need to be defined as the same resource. Maybe I won't need to worry about `GET /jobs/?query_params` ...

2. And in terms of security/access control, I'm not sure how AWS API Gateway would integrate with the PSC.

**Comment by yuanzhou** [comment]
Resource from Matt: https://aws.amazon.com/blogs/security/how-to-enhance-amazon-cloudfront-origin-security-with-aws-waf-and-aws-secrets-manager/

**Comment by yuanzhou** [comment]
- Add WAF ACL and attach to API Gateway to control IPs
- Create lambda function to forward requests to API running on PSC VM
- Create NAT in the current VPC with private subnet and associate with the lambda function
- PSC VM only allow the Elastic IP of the private subnet

**Comment by yuanzhou** [comment]
https://aws.amazon.com/blogs/compute/using-aws-lambda-iam-condition-keys-for-vpc-settings/

**Comment by shirey** [comment]
After further review and discussion with Juan we've decided to not put this behind the AWS Gateway.

**Comment by yuanzhou** [comment]
From Juan:
>Domain split between HTTP/WS/“Passthrough”
Passthrough here refers to the traffic that has to go through to JupyterLab (and any other interactive software)
HTTP/WS would live under AWS API Gateway
Passthrough traffic would have to be done outside of the context of the AWS API Gateway
Traffic would have to be opened up to the public for that particular “passthrough” domain.
Development effort would have to be spent on modifying the passthrough URLs.
Regardless of the option that we choose here, we wouldn’t be able to leverage the AWS API Gateway Globus authentication for the “passthrough” functionality anyway, as I don’t have any control over the headers/cookies that JupyterLab sets. 

>we can proceed with setting up AWS API REST/Websockets for everything except the /passthrough routes.
They can have different domain names.

We'll have the following domains:
- `ws-workspaces-api.dev.hubmapconsortium.org` and `workspaces-api.dev.hubmapconsortium.org` on DEV
- `ws-workspaces.api.hubmapconsortium.org` and `workspaces.api.hubmapconsortium.org` on PROD

**Comment by shirey** [comment]
This is complete for the RESTful endpoints, will track the work for web sockets here: https://github.com/hubmapconsortium/devops/issues/21

**Comment by yuanzhou** [comment]
Update: AWS API Gateway doesn't support websocket proxy to another backend websocket. We'll be using nginx on-prem to handle the call on PSC.

**Comment by yuanzhou** [comment]
FYI @shirey we have a working version on DEV now. PSC will get the SSL cert generated for PROD and I'll coordinate with the redeployment via PR https://github.com/hubmapconsortium/ingest-api/pull/164

For testing demo: https://www.piesocket.com/websocket-tester# and connect to `wss://ws-workspaces-api.dev.hubmapconsortium.org/jobs/`

We can also use a simple html client:
```
<html>
<script>
    document.cookie = 'token=b26901170afc7bb9eaeb4430898a93d4da520ee3'
    //let socket = new WebSocket("ws://hivevm191.psc.edu:5050/jobs/1/",[]);
    let socket = new WebSocket("wss://ws-workspaces-api.dev.hubmapconsortium.org/jobs/",[]);
//     var ws = new WebSocket(
//     'http://localhost/auth',
//     [],
//     {
//         'headers': {
//             'Cookie': cookie.serialize('id', '496E66DD')
//         }
//     }
// );
    socket.onopen = function(e) {
      alert("[open] Connection established");
      alert("Sending to server");
      socket.send('{"action" : "getJobs"}');
    };
    socket.onmessage = function(event) {
        console.log(event.data)
    };
    socket.onclose = function(event) {
      if (event.wasClean) {
        alert(`[close] Connection closed cleanly, code=${event.code} reason=${event.reason}`);
      } else {
        // e.g. server process killed or network down
        // event.code is usually 1006 in this case
        alert('[close] Connection died');
      }
    };
    socket.onerror = function(error) {
      alert(`[error] ${error.message}`);
    };
</script>
</html>
```

**Comment by yuanzhou** [comment]
Working version on DEV: https://github.com/hubmapconsortium/devops/issues/21#issuecomment-1126189744
